name: open-erase
services:
  open-erase-server:
    container_name: open-erase-server
    image: open-erase-server
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - open-erase-db

  open-erase-db:
    container_name: open-erase-db
    image: postgres:18
    restart: always
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  open-erase-iso-builder:
    container_name: open-erase-iso-builder
    image: open-erase-iso-builder
    cap_add:
      - SYS_ADMIN
    stdin_open: true
    build:
      context: .
      dockerfile: iso-builder.Dockerfile
    ports:
      - "3001:3001"
    command: >
      sh -c "mkarchiso -v -w /tmp/archiso-tmp -o /iso/out /iso"

volumes:
  db:
    driver: local
