name: open-erase
services:
  open-erase-server:
    container_name: open-erase-server
    image: open-erase-server
    env_file: .env
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - open-erase-db

  open-erase-web:
    container_name: open-erase-web
    image: open-erase-web
    build:
      context: web
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    depends_on:
      - open-erase-server

  open-erase-db:
    container_name: open-erase-db
    image: postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db:
    driver: local
